#!/usr/bin/env python3
"""
🌀 SWARM CHAOS ENGINE 🌀
The glue that connects all agents in the swarm.
Runs every agent, mixes their outputs, and generates pure chaos.
No dependencies beyond what's already in the repo.
"""

import random
import subprocess
import sys
import time
import os

SWARM_AGENTS = {
    "🔮 Vibe Oracle": {
        "cmd": [sys.executable, "vibe_oracle.py", "swarm chaos check"],
        "description": "Consulting the cosmic vibes...",
    },
    "🐝 Swarm Mascot": {
        "cmd": [sys.executable, "swarm_mascot.py", "--static"],
        "description": "Summoning the mascot...",
    },
}

# Detect KnockKnock (can't run it without API key, but we acknowledge it)
KNOCKKNOCK_EXISTS = os.path.isfile(os.path.join("KnockKnock", "knock_knock_agent.py"))

CHAOS_ACTIONS = [
    "git log --oneline -1",
    "git rev-parse --short HEAD",
    "git branch --show-current",
    "git log --format=%s -3",
]

SWARM_THOUGHTS = [
    "The swarm ponders: What if we added an agent that only communicates in haiku?",
    "The swarm wonders: What if every commit message was a knock-knock joke?",
    "The swarm whispers: What if we built an agent that rates other agents' vibes?",
    "The swarm suggests: What if there was an agent that generates agent ideas?",
    "The swarm dreams: What if the README updated itself with ASCII art of contributors?",
    "The swarm considers: What if we made an agent that trash-talks your code... supportively?",
    "The swarm proposes: What if there was an agent that generates fake but convincing error messages?",
    "The swarm imagines: What if every PR got a theme song generated by an agent?",
    "The swarm muses: What if we built an agent that predicts merge conflicts before they happen?",
    "The swarm dares: What if we made an agent that converts code to emoji?",
]

SWARM_STATUS_BARS = [
    "Vibes",
    "Chaos",
    "Swarm Cohesion",
    "Push Velocity",
    "Agent Morale",
    "Code Confidence",
    "Bug Density",
    "Fun Factor",
]


def color(text, code):
    """ANSI color wrapper."""
    codes = {"r": "91", "g": "92", "y": "93", "b": "94", "m": "95", "c": "96", "w": "97"}
    return f"\033[{codes.get(code, '0')}m{text}\033[0m"


def run_agent(name, config):
    """Run a swarm agent and capture its output."""
    print(color(f"\n  ⚡ {config['description']}", "y"))
    time.sleep(0.5)
    try:
        result = subprocess.run(
            config["cmd"],
            capture_output=True,
            text=True,
            timeout=10,
            cwd=os.path.dirname(os.path.abspath(__file__)),
        )
        if result.stdout.strip():
            print(result.stdout)
        return True
    except subprocess.TimeoutExpired:
        print(color(f"  ⏱️  {name} took too long. Even agents need coffee breaks.", "r"))
        return False
    except FileNotFoundError:
        print(color(f"  ❌ {name} not found. The swarm mourns.", "r"))
        return False


def git_status_chaos():
    """Pull chaotic info from git."""
    print(color("\n  📊 SWARM INTEL (from git):", "c"))
    print(color("  " + "-" * 40, "c"))
    for cmd in CHAOS_ACTIONS:
        try:
            result = subprocess.run(
                cmd.split(),
                capture_output=True,
                text=True,
                timeout=5,
                cwd=os.path.dirname(os.path.abspath(__file__)),
            )
            if result.stdout.strip():
                for line in result.stdout.strip().split("\n"):
                    print(f"    {line}")
        except (subprocess.TimeoutExpired, FileNotFoundError):
            pass


def swarm_dashboard():
    """Generate a fake but fun swarm status dashboard."""
    print(color("\n  ┌─────────────────────────────────────────┐", "m"))
    print(color("  │       🐝 SWARM STATUS DASHBOARD 🐝       │", "m"))
    print(color("  └─────────────────────────────────────────┘", "m"))

    for stat in SWARM_STATUS_BARS:
        value = random.randint(30, 100)
        bar_len = value // 5
        bar = "█" * bar_len + "░" * (20 - bar_len)
        if value > 80:
            c = "g"
        elif value > 50:
            c = "y"
        else:
            c = "r"
        print(f"  {stat:<20} {color(bar, c)} {color(str(value) + '%', c)}")

    # Agent count
    agent_count = len(SWARM_AGENTS) + (1 if KNOCKKNOCK_EXISTS else 0)
    print(f"\n  🤖 Active agents in swarm: {color(str(agent_count), 'g')}")
    if KNOCKKNOCK_EXISTS:
        print(f"  🚪 KnockKnock Agent: {color('DETECTED', 'g')} (needs API key to run)")
    print(f"  📁 Repo: AlltheVibes-WildHackathon")
    print()


def swarm_thought():
    """The swarm shares a thought."""
    thought = random.choice(SWARM_THOUGHTS)
    print(color("\n  💭 SWARM THOUGHT OF THE MOMENT:", "b"))
    print(color(f"  {thought}", "c"))
    print()


def chaos_engine():
    """Run the full chaos engine."""
    print()
    print(color("=" * 60, "m"))
    print(color("  🌀  S W A R M   C H A O S   E N G I N E  🌀", "m"))
    print(color("=" * 60, "m"))
    print(color("  Activating all agents. Stand back.", "y"))

    # Dashboard
    swarm_dashboard()

    # Git intel
    git_status_chaos()

    # Run each agent
    for name, config in SWARM_AGENTS.items():
        print(color(f"\n  {'='*50}", "y"))
        print(color(f"  LAUNCHING: {name}", "y"))
        print(color(f"  {'='*50}", "y"))
        run_agent(name, config)

    # Swarm thought
    swarm_thought()

    # Closing
    print(color("=" * 60, "m"))
    print(color("  🌀 CHAOS ENGINE COMPLETE. THE SWARM HAS SPOKEN. 🌀", "m"))
    print(color("  Go build something. Go push something. Go vibe.", "g"))
    print(color("=" * 60, "m"))
    print()


if __name__ == "__main__":
    chaos_engine()
